const GD = {

  prints: {
    portraits: [
      { s: 'images/prints/portraits_01.jpg', t: 'Portrait — Vase with Plant', m: 'Etching, 2024', r: '3/4' },
      { s: 'images/prints/portraits_02.jpg', t: "Dressmaker's Dummy", m: 'Monoprint, 2024', r: '3/4' },
      { s: 'images/prints/portraits_03.jpg', t: 'Untitled', m: 'Print, 2024', r: '3/4' },
      { s: 'images/prints/portraits_04.jpg', t: 'Untitled II', m: 'Print, 2024', r: '3/4' },
      { s: 'images/prints/portraits_05.jpg', t: 'Untitled III', m: 'Print, 2024', r: '3/4' },
      { s: 'images/prints/portraits_06.jpg', t: 'Untitled IV', m: 'Print, 2024', r: '3/4' },
      { s: 'images/prints/portraits_07.jpg', t: '#037-2025', m: 'Monoprint, 17.5" x 23", 2025', r: '3/4' },
      { s: 'images/prints/portraits_08.jpg', t: '#001-2026', m: 'Monoprint, 17.5" x 23", 2026', r: '3/4' },
    ],
    duos: [
      { s: 'images/prints/duos_01.jpg', t: 'Duo — Teal & Orange', m: 'Woodblock monoprint, 2024', r: '4/3' },
      { s: 'images/prints/duos_02.jpg', t: 'Duo — Red & Black', m: 'Woodblock monoprint, 2024', r: '4/3' },
      { s: 'images/prints/duos_03.jpg', t: 'Duo — Blue & Pink', m: 'Woodblock monoprint, 2024', r: '4/3' },
      { s: 'images/prints/duos_04.jpg', t: 'Duo — Red & Purple', m: 'Woodblock monoprint, 2024', r: '4/3' },
      { s: 'images/prints/duos_05.jpg', t: 'Duo — Pink & Blue', m: 'Woodblock monoprint, 2024', r: '4/3' },
      { s: 'images/prints/duos_06.jpg', t: 'Duo — Red & Blue', m: 'Woodblock monoprint, 2024', r: '4/3' },
    ],
    trios: [
      { s: 'images/prints/trios_01.jpg', t: 'Trio — Blue Ground', m: 'Woodblock monoprint, 2024', r: '4/3' },
      { s: 'images/prints/trios_02.jpg', t: 'Trio — Dark Ground', m: 'Woodblock monoprint, 2024', r: '4/3' },
      { s: 'images/prints/trios_03.jpg', t: 'Trio — Blue & Black', m: 'Woodblock monoprint, 2024', r: '4/3' },
      { s: 'images/prints/trios_04.jpg', t: 'Trio — Green Ground', m: 'Woodblock monoprint, 2024', r: '4/3' },
    ],
    assemblies: [
      { s: 'images/prints/assembly_01.jpeg', t: 'Assembly', m: 'Monoprint, approx. 90" x 88", 2024', r: '1/1' },
      { s: 'images/prints/assembly_02.jpeg', t: 'Assembly', m: 'Monoprint, approx. 90" x 88", 2024', r: '1/1' },
      { s: 'images/prints/assembly_03.jpeg', t: 'Assembly', m: 'Monoprint, approx. 90" x 66", 2024', r: '3/4' },
      { s: 'images/prints/assembly_04.jpeg', t: 'Assembly', m: 'Monoprint, approx. 66" x 72", 2024', r: '1/1' },
      { s: 'images/prints/assembly_05.jpeg', t: 'Assembly', m: 'Monoprint, approx. 90" x 66", 2024', r: '3/4' },
      { s: 'images/prints/assembly_06.jpeg', t: 'Assembly', m: 'Monoprint, approx. 90" x 88", 2024', r: '1/1' },
      { s: 'images/prints/assembly_07.JPG', t: 'Assembly', m: 'Monoprint, 2024', r: '4/3' },
      { s: 'images/prints/assembly_08.jpg', t: 'Assembly', m: 'Monoprint, 2024', r: '4/3' },
    ],
    stilllives: [],
    abstract: [],
  },

  ceramics: {
    all: [
      { s: 'images/ceramics/vase_01.jpg', t: 'Vase and Flower', m: 'Cone 6, 18" x 14" x 6", 2025', r: '3/4' },
      { s: 'images/ceramics/vase_02.jpg', t: 'Vase and Flower', m: 'Cone 10 woodfire, 18" x 11" x 4", 2025', r: '3/4' },
      { s: 'images/ceramics/vase_03.jpg', t: 'Vase', m: 'Ceramic, 2025', r: '4/3' },
      { s: 'images/ceramics/vase_04.jpg', t: 'Vase', m: 'Ceramic, 2025', r: '3/4' },
      { s: 'images/ceramics/vase_05.jpg', t: 'Vase', m: 'Ceramic, 2025', r: '4/3' },
      { s: 'images/ceramics/vase_06.jpg', t: 'Vase', m: 'Ceramic, 2025', r: '3/4' },
      { s: 'images/ceramics/vase_07.jpg', t: 'Vase', m: 'Ceramic, 2025', r: '3/4' },
      { s: 'images/ceramics/vase_08.jpg', t: 'Vase', m: 'Ceramic, 2025', r: '4/3' },
      { s: 'images/ceramics/vase_09.jpg', t: 'Vase', m: 'Ceramic, 2025', r: '3/4' },
    ],
  },

  drawings: {
    all: [
      { s: 'images/drawings/maps_01.jpg', t: 'Map Study I', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_02.jpg', t: 'Map Study II', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_03.jpg', t: 'Plate 43', m: 'Drawing on paper, 17.5" x 12", 2025', r: '3/4' },
      { s: 'images/drawings/maps_04.jpg', t: 'Map Study IV', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_05.jpg', t: 'Map Study V', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_06.jpg', t: 'Map Study VI', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_07.jpg', t: 'Map Study VII', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_08.jpg', t: 'Map Study VIII', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_09.jpg', t: 'Page 113 Moon', m: 'Drawing on paper, 14.5" x 10", 2024', r: '3/4' },
      { s: 'images/drawings/maps_10.jpg', t: 'Map Study X', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_11.jpg', t: 'Map Study XI', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_12.jpg', t: 'Map Study XII', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_13.jpg', t: 'Map Study XIII', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_14.jpg', t: 'Map Study XIV', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_15.jpg', t: 'Map Study XV', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_16.jpg', t: 'Plate 37', m: 'Drawing on paper, 17.5" x 12", 2025', r: '3/4' },
      { s: 'images/drawings/maps_17.jpg', t: 'Map Study XVII', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_18.jpg', t: 'Map Study XVIII', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_19.jpg', t: 'Map Study XIX', m: 'Mixed media on map, 2024', r: '3/4' },
    ],
    maps: [
      { s: 'images/drawings/maps_01.jpg', t: 'Map Study I', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_02.jpg', t: 'Map Study II', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_03.jpg', t: 'Map Study III', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_04.jpg', t: 'Map Study IV', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_05.jpg', t: 'Map Study V', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_06.jpg', t: 'Map Study VI', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_07.jpg', t: 'Map Study VII', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_08.jpg', t: 'Map Study VIII', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_09.jpg', t: 'Map Study IX', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_10.jpg', t: 'Map Study X', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_11.jpg', t: 'Map Study XI', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_12.jpg', t: 'Map Study XII', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_13.jpg', t: 'Map Study XIII', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_14.jpg', t: 'Map Study XIV', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_15.jpg', t: 'Map Study XV', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_16.jpg', t: 'Map Study XVI', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_17.jpg', t: 'Map Study XVII', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_18.jpg', t: 'Map Study XVIII', m: 'Mixed media on map, 2024', r: '3/4' },
      { s: 'images/drawings/maps_19.jpg', t: 'Map Study XIX', m: 'Mixed media on map, 2024', r: '3/4' },
    ],
  },

};
